# Generated by Django 3.1.5 on 2021-05-03 23:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='StBus_app1/media')),
                ('role', models.CharField(choices=[('none', 'none'), ('student', 'student'), ('unemployed', 'unemployed')], max_length=10)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptype', models.CharField(choices=[('working day', 'working day'), ('holidays ', 'holidays')], max_length=11)),
                ('departure', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='non_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('month', 'month'), ('6 months', '6 months'), ('year', 'year')], max_length=8)),
                ('subprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.departures')),
                ('dest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(choices=[('2h', '2h'), ('day', 'day')], max_length=3)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.zones')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Profiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.subscription_types')),
            ],
        ),
        migrations.AddField(
            model_name='subscription_types',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.zones'),
        ),
        migrations.CreateModel(
            name='Single_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('validfrom', models.DateTimeField()),
                ('amount', models.PositiveIntegerField(default='1')),
                ('Profiles_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('non_users_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_api.non_users')),
                ('ticket_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.ticket_types')),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.zones'),
        ),
    ]
