# Generated by Django 3.1.5 on 2021-06-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20210506_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_ticket',
            name='non_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.non_users'),
        ),
    ]
