# Generated by Django 3.1.5 on 2021-07-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_auto_20210712_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='line_no',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='non_users',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('student', 'student'), ('unemployed', 'unemployed')], max_length=10, null=True),
        ),
    ]
