# Generated by Django 3.1.5 on 2021-07-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_auto_20210729_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='line_no',
            field=models.PositiveIntegerField(default='1', unique=True),
        )
    ]
