# Generated by Django 3.1.5 on 2021-07-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0008_auto_20210729_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='active',
            field=models.BooleanField(default=True),
        ),
      
    ]
