# Generated by Django 3.1.5 on 2021-07-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0009_auto_20210729_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_ticket',
            name='amount',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
