# Generated by Django 3.1.5 on 2021-07-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0010_auto_20210729_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departures',
            name='deptype',
            field=models.CharField(choices=[('working_day', 'working_day'), ('holidays', 'holidays')], max_length=11),
        ),
    ]
