# Generated by Django 3.1.5 on 2021-08-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0011_auto_20210731_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_types',
            name='active',
            field=models.BooleanField(default=True),
        )
    ]
