# Generated by Django 3.1.5 on 2021-07-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_auto_20210601_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departures',
            name='deptype',
            field=models.CharField(choices=[('working_day', 'working_day'), ('holidays ', 'holidays')], max_length=11),
        ),
    ]
